// <auto-generated />
using System;
using MCSP.MyAirport.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MCSP.MyAirport.EF.Migrations
{
    [DbContext(typeof(MyAirportContext))]
    [Migration("20200425175444_UniqueConstraints")]
    partial class UniqueConstraints
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MCSP.MyAirport.EF.Bagage", b =>
                {
                    b.Property<int>("BagageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_BAGAGE")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Classe")
                        .HasColumnType("char(1)");

                    b.Property<string>("CodeIata")
                        .IsRequired()
                        .HasColumnType("char(12)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .HasColumnType("char(3)");

                    b.Property<string>("Escale")
                        .HasColumnType("char(3)");

                    b.Property<bool?>("Prioritaire")
                        .HasColumnType("bit");

                    b.Property<string>("Ssur")
                        .HasColumnType("char(3)");

                    b.Property<string>("Sta")
                        .HasColumnType("char(1)");

                    b.Property<int?>("VolId")
                        .HasColumnType("int");

                    b.HasKey("BagageId");

                    b.HasIndex("VolId");

                    b.HasIndex("CodeIata", "DateCreation")
                        .IsUnique();

                    b.ToTable("Bagages");
                });

            modelBuilder.Entity("MCSP.MyAirport.EF.Vol", b =>
                {
                    b.Property<int>("VolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_VOL")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cie")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<string>("Des")
                        .HasColumnType("char(3)");

                    b.Property<DateTime>("Dhc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imm")
                        .HasColumnType("char(6)");

                    b.Property<string>("Lig")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<short?>("Pax")
                        .HasColumnType("smallint");

                    b.Property<string>("Pkg")
                        .HasColumnType("char(3)");

                    b.HasKey("VolId");

                    b.HasIndex("Cie", "Lig", "Dhc")
                        .IsUnique();

                    b.ToTable("Vols");
                });

            modelBuilder.Entity("MCSP.MyAirport.EF.Bagage", b =>
                {
                    b.HasOne("MCSP.MyAirport.EF.Vol", "Vol")
                        .WithMany("Bagages")
                        .HasForeignKey("VolId");
                });
#pragma warning restore 612, 618
        }
    }
}
